// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxhmzhseczfzbdmhztys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4aG16aHNlY3pmemJkbWh6dHlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMDk2NjcsImV4cCI6MjA1ODU4NTY2N30.onh7HQg84sAiQuPU7CH6fq0CllfC06zNzjUey4YE3ug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);